### PR TITLE
Release preparation

### LINKED ISSUE #33: Update skew and kurtosis to return NaN when array is 100% duplicated
Crick was originally written to be compatible with scipy v1.7. 

Now with a more modern scipy (v.19), skew and kurtosis return NaN when `nunique(array) == 1`. Previously in Scipy and currently in crick, the kurtosis values of a single-unique-value array are either 0 when the `fisher` parameter is True or or 3 when it is False. The presence of the issue is demonstrated in the test suite & the case is currently marked as an `xfail`: https://github.com/dask/crick/blob/master/crick/tests/test_stats.py#L72

Basically, (in pure C), we need to be able to detect the number of unique elements in the tdigest array and set the skew and kurtosis functions to return NaN in those cases.

This issue can be considered a "part two" of #31.

### PR DESCRIPTION
**Pull request by milesgranger**
Contains work from:
- #32 
- #35 

And a fix to close #33

### CODE REVIEW

**Comment by milesgranger** [comment]
@jrbourbeau @fjetter I'm not sure who to ping here for a review, I think the others involved are no longer wanting to be involved so hesitate to tag them.

**Review by fjetter — APPROVED** [review]
@jrbourbeau did you already set up the pypi credentials in this repo? I don't have access to the pypi package

**Comment by jrbourbeau** [comment]
Thanks @milesgranger. I'll add PyPI creds and merge this PR

**Comment by milesgranger** [comment]
Last commit failure is [not related, timeout error](https://github.com/dask/crick/actions/runs/6167907186/job/16739601610?pr=39#step:3:748)

**Comment by milesgranger** [comment]
@jrbourbeau I don't have permissions to view settings/credentials or make a release for that matter. Would you be able to handle that, and/or grant me the appropriate permissions?

**Pull request merged**
